name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
      
      - name: Update version from tag
        run: |
          # Extract version from tag
          VERSION=${{ github.ref_name }}
          # Replace version in setup.py
          sed -i "s/version=\"[^\"]*\"/version=\"${VERSION}\"/g" setup.py
      
      - name: Fix src layout issues
        run: |
          if [ -d "src" ]; then
            echo "Using src layout"
          else
            # Create pyproject.toml to handle the flat layout
            cat > pyproject.toml << 'EOF'
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mcp_google_contacts_server"]

[tool.setuptools.package-data]
mcp_google_contacts_server = ["*.py"]
EOF
            
            # Create a package directory and copy Python files
            mkdir -p mcp_google_contacts_server
            cp *.py mcp_google_contacts_server/
            # Create an __init__.py file
            touch mcp_google_contacts_server/__init__.py
          fi
      
      - name: Build package
        run: python -m build
      
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
