name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
      
      - name: Set execute permissions for scripts
        run: |
          chmod +x scripts/update_version.sh
          chmod +x scripts/fix_layout.sh
      
      - name: Update version from tag
        run: ./scripts/update_version.sh ${{ github.ref_name }}
      
      - name: Fix src layout issues
        run: ./scripts/fix_layout.sh
      
      - name: Build package
        run: python -m build
      
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
